export const queryKeys = {
  // admin page
  AdminAuth: "AdminAuth",
  GetFullPage: "GetFullPage",
  VacancyFullPage: "VacancyFullPage",
  PutVacancyFullPage: "PutVacancyFullPage",
  PutHomePageData: "PutHomePageData",
  deleteImage: "deleteImage",
  uploadImage: "uploadImage",
  GetCareersPage: "GetCareersPage",
  UpdateCareersPage: "UpdateCareersPage",
  getPortfolio: "getPortfolio",
  updatePortfolio: "updatePortfolio",
  getPortfolioPage: "getPortfolioPage",
  updatePortfolioPage: "updatePortfolioPage",
  deleteTicketAndVacancy: "deleteTicketAndVacancy",
  deleteArticle: "deleteArticle",
  updateBlogPage: "updateBlogPage",
  getBlogPage: "getBlogPage",
  getBlogArticle: "getBlogArticle",
  postArticle: "postArticle",
  views: "views",
  getFaqPage: "getFaqPage",
  updateFaqPage: "updateFaqPage",
  getAboutUsPage: "getAboutUsPage",
  updateAboutUsPage: "updateAboutUsPage",
  getServiceMobilePage: "getServiceMobilePage",
  updateServiceMobilePage: "updateServiceMobilePage",
  getServiceWebPage: "getServiceWebPage",
  updateServiceWebPage: "updateServiceWebPage",
  // home page
  getFullHomePage: "getFullHomePage",
  getCareerPage: "getFullCareerPage",
  getVacancyPage: "getFullVacancyPage",
  // valid
  validToken: "validToken",
};
