const themes = {
  primary: {
    spacing: {
      small: "0.3em",
      primary: "0.8em",
      logosGap: "1.18em",
      septenary: "1.3em",
      tertiary: "2em",
      logo: "13em",
      headerNavVertical: "2em",
      headerNavVerticalTablet: "2em",
      adminWithinBlocks: "3em",
      headerNavHorizontal: "5em",
      topButtonSpace: "4.5em",
      btnHeight: "7em",
      btnWidth: "16em",
      aboutUsCard: "30%",
      aboutUsCardMobile: "22em",
      aboutUsDescription: "8em",
      cardPartners: "14em",
      btwLogoAndMenu: "8.5em",
      servicesGlobalMarginBetweenBlocks: "12.5em",
      servicesMarginBetweenBlocks: "16.6em",
      servicesMarginBetweenBlocksTablet: "8em",
      servicesMarginBetweenBlocksMobile: "4em",
      servicesMarginBetweenFooter: "10.3em",
      servicesMarginBetweenFooterTablet: "6.5em",
      servicesMarginBetweenFooterMobile: "5.8em",
    },
    font: {
      family: {
        barlow: "'Barlow', sans-serif",
        sourceCode: "'Source Code Pro', monospace",
        mulish: "'Roboto', sans-serif",
        gilroy: "'Gilroy', sans-serif",
        namu: "'NAMU', sans-serif",
        openSans: "'Open Sans', sans-serif",
        inter: "'Inter', sans-serif",
        pressStart: "'Press Start 2P', cursive",
      },
      weight: {
        light: 300,
        normal: 400,
        medium: 500,
        semiBold: 600,
        bold: 700,
        extraBold: 800,
        heavy: 900,
      },
      size: {
        careersTitle: "6.1em",
        smallerCareersTitle: "4em",
        reviewSmallText: "1.03em",
        homeFooterButton: "0.285em",
        hexadecimal: "0.375em",
        septenary: "0.6em",
        quinary: "0.72em",
        fourteenth: "0.875em",
        articleViews: "1.17em",
        vistaco: "1.1em",
        tertiary: "1.2em",
        primary: "1em",
        aboutUsBelieveText: "1.35em",
        aboutUsCardText: "1.3em",
        linkText: "1.4em",
        oneAndHalf: "1.5em",
        buttonText: "1.5em",
        articleSubtitle: "1.6em",
        menuElement: "1.7em",
        adminMenuElement: "0.8em",
        articleTagDescription: "1.8em",
        feedbackName: "1.83em",
        careersFormLaptop: "1.3em",
        adminButton: "1.8em",
        faqQuestion: "1.669em",
        faqAnswer: "1.335em",
        oneAndNine: "1.9em",
        secondary: "2em",
        blogArticleTitle: "2.2em",
        quaternary: "2.6em",
        articleDescription: "3.15em",
        smallAboutSubtitle: "2.7em",
        aboutUsSubtitle: "3.35em",
        mainPagePhoto: "2.68em",
        ourWorkText: "3.61vw",
        ourWorkTextBig: "3.5em",
        reviewTitle: "2.5em",
        reviewText: "1.334em",
        projectLink: "1.165em",
        articleTitle: "5em",
        bigTitle: "4.125em",
        headerLinkText: "1.3em",
        authorDate: "0.83em",
        mainBlogTitle: "2.83em",
        mainBlogDescription: "18px",
        mainBlogAuthor: "14px",
        smallBlogTitle: "21px",
        smallBlogDescription: "14px",
        secondaryArticleTitle: "30px",
        secondaryArticleDescription: "20px",
        secondaryArticleAuthor: "16px",
        secondaryServicesTitle: "3.33em",
        secondaryServicesSubTitle: "2.67em",
        secondaryServicesText: "1.225em",
        email: "16px",
        homeHeader: "8.334em",
        homeHeaderTablet: "8.15em",
        homeHeaderPc: "8.2em",
        homeHeaderPcHd: "7.9em",
        homeSubtitle: "6.2em",
        homeSmallTitle: "5.6em",
        homeCardSubtitle: "5.68em",
        serviceTitle: "5.5em",
        serviceSubtitle: "2.5em",
        tabletServiceTitle: "4em",
        homeMainSubtitle: "2.167em",
        inBlockMaxTableText: "1.3em",
        faqMobileTitle: "3em",
        portfolioMobile: "3.8em",
        notFoundPageTitlePc: "2.8em",
        notFoundPageTitleTablet: "1.8em",
        webAuditSubtitle: "3.33em",
        webAuditSubtitlePC: "3.5em",
        webAuditSubtitleTabletLandscape: "2.5em",
        webAuditSubtitleTabletPortrait: "2.2em",
        webAuditSubtitleMobile: "2.3em",
      },
    },
    colors: {
      mainGradientColor1: "#d6ffbb",
      mainGradientColor2: "#5869dd",
      headerBorder: "#8F8E93",
      headerBorderHover: "#F2EA86",
      gray: "#535353",
      cyanBlue: "#0070f3",
      lightGray: "#E5E5E5",
      separator: "#CDCDCD",
      decorationText: "#C7FB9C",
      quinary: "#FFA046",
      primary: "#000",
      secondary: "#fff",
      starActive: "#FBA446",
      starDisable: "#EEE6DD",
      previewArticleText: "#BDC4FA",
      septenary: "#A9CDF5",
      blue: "#85BEFD",
      linkBlue: "#3C95F9",
      darkBlue: "#5869DD",
      calculatorDarkBlue: "#4654B1",
      adminBlue: "#095AF8",
      tagBg: "#3749C5",
      hoveredBlogTag: "#3749C5",
      cardDarkGreen: "#90e645",
      orange: "#FFC061",
      green: "#B6FD7A",
      lightBlue: "#436C9B",
      lighten: {
        blue: "#A6D0FF",
        orange: "#FFCE85",
        green: "#CAFF9D",
      },
      lightShadows: "lightgray",
      errorText: "#ea0000",
      adminRed: "#F80909",
      grayBack: "#EFEEEE",
      comment: "#8F8E93",
      darkedGrayBack: "#DDDBDB",
      deleteButton: "#F80909",
      feedbackRole: "#A9CDF5",
      black: "#000",
      authorGrey: "#716D6D",
      darkBlueBlockchain: "#392770",
      blogDarkText: "#272C2F",
      blogArticleText: "#535557",
      blogBackground: "#f1efed",
      blogFooter: "#EBE9EB",
      blogDropdownHover: "#F8F7F5",
      careerBackground: "#f1efed",
      portfolioBg: "#F1EFED",
      portfolioHover: "#F2EA86",
      faqBorder: "#B5B5B5",
      bigDigit: "#F0EFED",
      lightGreyBorder: "#D9D9D9",
      inputGrey: "#787877",
      ourWork: "#A7A6A9",
      serviceHighlight: "#BABABA",
      deleteImageHover: "#ad1313",
      adminInputBorder: "#A9A5A4",
      whatsApp: "#4DA303",
      telegram: "#34AADF",
      calculatorButtonBorderBg: "#b2b2b2",
      calculatorButtonBg: "#e7e5e3",
      calculatorHorizontalLine: "#C6C6C6",
      calculatorEmailPlaceholder: "#797877",
      modalFormBackground: "rgba(241, 239, 237, 0.7)",
      careersPlaceholder: "rgba(0, 0, 0, 0.5)",
    },
    media: {
      minTabletPortrait: "(min-width: 768px)",
      maxTablet: "(max-width: 768px)",
      minTabletLandScape: "(min-width: 992px)",
      minTablet: "(max-width: 625px)",
      minLaptop: "(min-width: 1200px)",
      minPC: "(min-width: 1500px)",
      minPCFullHD: "(min-width: 1800px)",
      minPCTwoThousand: "(min-width: 2560px)",
      minPCFourThousand: "(min-width: 3840px)",
      maxServiceMobile: "(max-width: 1425px)",
      maxServiceWeb: "(max-width: 1400px)",
      maxPCFullHD: "(max-width: 1800px)",
      maxPCFourThousand: "(max-width: 3840px)",
      maxPCTwoThousand: "(max-width: 2560px)",
      maxLowScreenMobile: "(max-width: 475px)",
      maxLowestScreenMobile: "(max-width: 374px)",
      maxLowMobileHeight: "(max-height: 610px)",
      estiomationFormWidth: "(max-width: 570px)",
      maxMobile: "(max-width: 767px)",
      minMobile: "(min-width: 767px)",
      maxMobileHeight: "(max-height: 710px)",
      maxTabletPortrait: "(max-width: 992px)",
      maxTabletLandScape: "(max-width: 1200px)",
      maxLaptop: "(max-width: 1500px)",
      maxMobilePortrait: "(max-width: 550px)",
      onlyTabletPortrait: "(min-width: 768px) and (max-width: 992px)",
      onlyTabletLandScape: "(min-width: 992px) and (max-width: 1200px)",
      onlyLaptop: "(min-width: 1200px) and (max-width: 1500px)",
      onlyPC: "(min-width: 1500px) and (max-width: 1800px)",
    },
  },
};

export default themes;
