const themes = {
  primary: {
    spacing: {
      small: "0.3em",
      primary: "0.8em",
      septenary: "1.3em",
      tertiary: "2em",
      logo: "13em",
      headerNavVertical: "2.5em",
      adminWithinBlocks: "3em",
      headerNavHorizontal: "5em",
      topButtonSpace: "4.5em",
      btnHeight: "7em",
      btnWidth: "16em",
      aboutUsCard: "30%",
      aboutUsCardMobile: "22em",
      aboutUsDescription: "8em",
      cardPartners: "14em",
      btwLogoAndMenu: "8.5em",
    },
    font: {
      family: {
        barlow: "'Barlow', sans-serif",
        roboto: "'Roboto', sans-serif",
        sourceCode: "'Source Code Pro', monospace",
        mulish: "'Roboto', sans-serif",
        gilroy: "'Gilroy', sans-serif",
      },
      weight: {
        light: 300,
        normal: 400,
        medium: 500,
        semiBold: 600,
        bold: 700,
        extraBold: 800,
        heavy: 900,
      },
      size: {
        hexadecimal: "0.375em",
        septenary: "0.6em",
        fourteenth: "0.875em",
        quinary: "0.72em",
        vistaco: "1.1em",
        tertiary: "1.2em",
        primary: "1em",
        linkText: "1.4em",
        buttonText: "1.5em",
        menuElement: "1.7em",
        secondary: "2em",
        quaternary: "2.6em",
        bigTitle: "4.125em",
      },
    },
    colors: {
      decorationText: "#C7FB9C",
      quinary: "#FFA046",
      primary: "#000",
      secondary: "#fff",
      starActive: "#FBA446",
      starDisable: "#EEE6DD",
      septenary: "#A9CDF5",
      blue: "#85BEFD",
      linkBlue: "#3C95F9",
      cardDarkGreen: "#90e645",
      orange: "#FFC061",
      green: "#B6FD7A",
      lightBlue: "#436C9B",
      lighten: {
        blue: "#A6D0FF",
        orange: "#FFCE85",
        green: "#CAFF9D",
      },
      lightShadows: "lightgray",
      errorText: "#ea0000",
      grayBack: "#EFEEEE",
      comment: "#8F8E93",
      darkedGrayBack: "#DDDBDB",
      deleteButton: "#F80909",
      feedbackRole: "#A9CDF5",
    },
    media: {
      minTabletPortrait: "(min-width: 768px)",
      maxTablet: "(max-width: 768px)",
      minTabletLandScape: "(min-width: 992px)",
      minTablet: "(max-width: 625px)",
      minLaptop: "(min-width: 1200px)",
      minPC: "(min-width: 1500px)",
      minPCFullHD: "(min-width: 1800px)",
      maxPCFullHD: "(max-width: 1800px)",
      maxLowScreenMobile: "(max-width: 475px)",
      maxMobile: "(max-width: 768px)",
      maxTabletPortrait: "(max-width: 992px)",
      maxTabletLandScape: "(max-width: 1200px)",
      maxLaptop: "(max-width: 1500px)",
      onlyTabletPortrait: "(min-width: 768px) and (max-width: 991px)",
      onlyTabletLandScape: "(min-width: 992px) and (max-width: 1199px)",
      onlyLaptop: "(min-width: 1200px) and (max-width: 1500px)",
    },
  },
};

export default themes;
