const themes = {
  primary: {
    spacing: {
      small: "0.3em",
      horizontalGap: "0.6em",
      primary: "0.8em",
      verticalGap: "1em",
      septenary: "1.3em",
      oneSix: "1.6em",
      tertiary: "2em",
      logo: "13em",
      headerNavVertical: "2.5em",
      adminWithinBlocks: "3em",
      headerNavHorizontal: "5em",
      topButtonSpace: "4.5em",
      btnHeight: "7em",
      btnWidth: "16em",
      aboutUsCard: "30%",
      aboutUsCardMobile: "22em",
      aboutUsDescription: "8em",
      cardPartners: "14em",
      btwLogoAndMenu: "8.5em",
    },
    font: {
      family: {
        sourceCode: "'Source Code Pro', monospace",
        montserrat: "'Montserrat', sans-serif",
        inter: "'Inter', sans-serif",
        goldman: "'Goldman', cursive",
      },
      weight: {
        light: 300,
        normal: 400,
        medium: 500,
        semiBold: 600,
        bold: 700,
        extraBold: 800,
        heavy: 900,
      },
      size: {
        hexadecimal: "0.375em",
        septenary: "0.6em",
        fourteenth: "0.875em",
        quinary: "0.72em",
        vistaco: "1.1em",
        tertiary: "1.2em",
        primary: "1em",
        aboutUsCardText: "1.3em",
        linkText: "1.4em",
        oneAndHalf: "1.5em",
        buttonText: "1.5em",
        greenSubheader: "1.6em",
        menuElement: "1.7em",
        secondary: "2em",
        quaternary: "2.6em",
        bigHeader: "2.9em",
        bigTitle: "5rem",
      },
    },
    colors: {
      textColor: "#fff",
      purpleBack: "#322262",
      allGreen: "#90e745",
      headerBorder: "#3a96fb"
    },
    media: {
      minTabletPortrait: "(min-width: 768px)",
      minTabletLandScape: "(min-width: 992px)",
      minTablet: "(max-width: 625px)",
      minLaptop: "(min-width: 1200px)",
      minPC: "(min-width: 1500px)",
      minPCFullHD: "(min-width: 1800px)",
      maxPCFullHD: "(max-width: 1800px)",
      maxLowScreenMobile: "(max-width: 475px)",
      maxMobile: "(max-width: 768px)",
      maxTabletPortrait: "(max-width: 992px)",
      maxTabletLandScape: "(max-width: 1200px)",
      maxLaptop: "(max-width: 1500px)",
      onlyTabletPortrait: "(min-width: 768px) and (max-width: 991px)",
      onlyTabletLandScape: "(min-width: 992px) and (max-width: 1199px)",
      onlyLaptop: "(min-width: 1200px) and (max-width: 1500px)",
    },
  },
};

export default themes;
