name: Development workflow

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build for heroku
        run: docker buildx build --platform linux/amd64 -t cd-landing-frontend-stg . && docker tag cd-landing-frontend-stg registry.heroku.com/cd-landing-frontend-stg/web && docker push registry.heroku.com/cd-landing-frontend-stg/web && heroku container:release web -a cd-landing-frontend-stg

      