name: Development workflow

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./landing

    steps:
      - name: Development Code
        uses: actions/checkout@v3
      
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          args: deploy --dir=build --prod
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'cd-landing-frontend-stg'
          heroku_email: 'contact@codegenerationsoftware.com'
          stack: container
          docker_heroku_process_type: web
          usedocker: true
         
       