name: Deploy to Heroku

on:
  push:
    branches:
      - staging
    paths:
      - landing/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./landing

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 17.x

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      # - name: Deploy to Heroku
      #   run: |
      #     echo "machine api.heroku.com login ${{ secrets.HEROKU_API_KEY }}" >> ~/.netrc
      #     echo "machine git.heroku.com login ${{ secrets.HEROKU_API_KEY }}" >> ~/.netrc
      #     git init
      #     git config --global user.email "d4100kx@gmail.com"
      #     git config --global user.name "andreiradchenko"
      #     git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git  # Fix the Git repository URL
      #     git checkout -b main  # Create a new branch named 'main'
      #     git add .
      #     git commit -m "Deploy to Heroku from staging branch"
      #     git push -f heroku main:main
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          args: deploy --dir=build --prod
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'radchenko-cgs-landing'
          heroku_email: 'd4100kx@gmail.com'
        env:
          HD_PROJECT_PATH: 'landing'
